apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: database-replicaset
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: felipeoliveira22/banco-it_talent:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "BANCO_DADOS_IT_TALENT"
        ports:
        - containerPort: 3306
